### ISSUE TITLE
tallyco.in bugs/issues/suggestions

### ISSUE THREAD

**Issue by nil0x42** [djbooth007/tallycoin_connect#1]
Hi ! I just tested tallyco.in, amazing project idea. Therefore i found some bugs & would like to know if it is the right place to post them.

------------

### Here are bugs/issues/suggestions i found:

1- There is no way to delete an account
2- The `forgot password` feature sends us our password, meaning it's not encrypted in the DB (bcrypt hashing would be better)

**Comment by nil0x42** [comment]
Hum, so after using 'forgot password', it looks like i received a pass and are now able to log-in via e-mail..

Indeed, i received the same password i had created, so here is a 4th issue:
- passwords are not hashed in the database (i recommend bcrypt)

**Comment by djbooth007** [comment]
Sorry for late response. Github didnt send me a notification about your issue.

1. Login and navigate to Settings in the Admin dashboard. Then click 'close account'.

2. All private information, including passwords, are encrypted in the server database. Password is decrypted and checked upon logging in and for the 'forgot password' feature.
