### ISSUE TITLE
Umbrel App Store

### ISSUE THREAD

**Issue by ernez84** [djbooth007/tallycoin_connect#13]
When Tallycoin Connect is available in Umbrel (App Store)?

**Comment by djbooth007** [comment]
Tallycoin Connect was recently Dockerized by @dennisreimann and Umbrel requires apps to be contained in Docker.

@dennisreimann, do you know what else may need to be done to prepare for Umbrel app store?

**Comment by dennisreimann** [comment]
I haven't created an Umbrel app myself yet, but there's a decent [documentation](https://github.com/getumbrel/umbrel/tree/master/apps) and as you said the groundwork is laid.

If someone is willing to take this on I can assist.

**Comment by dennisreimann** [comment]
This can be closed now :)

**Comment by djbooth007** [comment]
Tallycoin Connect is now available in Umbrel. Closing this issue.
