### ISSUE TITLE
What is the default password on Umbrel?

### ISSUE THREAD

**Issue by CronusCipher** [djbooth007/tallycoin_connect#16]
When I want to enter the platform on http://umbrel.local:8123/ , I should enter the password while I did not set the password yet.
I tried my Umbrel password but not work.
Is there any default password?

**Comment by djbooth007** [comment]
By default, Tallycoin Connect is fully accessible without asking for a password to enter.

Adding a password is optional. If you already did this in the setup page, you'd need to use your chosen password, which could be different from the Umbrel password.
