### ISSUE TITLE
API description to communicate with tallycion

### ISSUE THREAD

**Issue by renepickhardt** [djbooth007/tallycoin_connect#21]
Hey I wanted to write a c-lighting plugin that woul allow the tallycoin application to talk to my lighting node and request invoices. but I would have to parse the javascript here to understand the API. do you have it documented somewhere?

**Comment by djbooth007** [comment]
Hi Rene.
I've added a description to the readme file.
https://github.com/djbooth007/tallycoin_connect/blob/master/README.md#how-does-tallycoin-connect-work

Let me know if you have any issues or my explanation is lacking.

**Comment by renepickhardt** [comment]
Looks good! I'll also have the current source code for reference I guess. Hope I find the time soon!

**Comment by djbooth007** [comment]
Awesome. Closing this issue.
